language: node_js
node_js: "6"

install: npm install
cache:
  directories:
    - "node_modules"


before_script:
  - npm install -g gulp-cli
script: gulp build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
