language: node_js
node_js: "8"

env:
  - CXX=g++-5
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-5
      - libgif-dev

install: npm install
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli
  - gulp -v
script:
  - NODE_ENV=production gulp build
  - echo $WEB_URL > ./build/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
