language: node_js
node_js: "8"

install: npm install
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli
script:
  - NODE_ENV=production gulp build
  - echo $WEB_URL > ./build/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
